---
title: "File Cleanup"
author: "Martin Gordon"
date: "5/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{R, messages=F}
library(tximport)
library(biomaRt)
library(rio)
library(dplyr)
library(tidyr)
library(readr)
library(DESeq2)
```


```{r}
samples_eg <- as.data.frame(matrix(data = c(
  "MCF7_miR-CTRL1.gene.FPKM", "MCF7_miR-CTRL2.gene.FPKM", "MCF7_miR-CTRL3.gene.FPKM","MCF7_miR-CTRL4.gene.FPKM",   "MCF7_miR-D1.gene.FPKM", "MCF7_miR-D2.gene.FPKM", "MCF7_miR-D3.gene.FPKM", "MCF7_miR-D4.gene.FPKM", 
  "Control", "Control", "Control", "Control", "Mutant",  "Mutant",  "Mutant",  "Mutant",
   "1",  "2", "3", "4", "1",  "2", "3", "4", 
  "~/Documents/MSC_project/data/MCF7_miR-CTRL1.gene.FPKM.xls",  "~/Documents/MSC_project/data/MCF7_miR-CTRL2.gene.FPKM.xls",
  "~/Documents/MSC_project/data/MCF7_miR-CTRL3.gene.FPKM.xls", "~/Documents/MSC_project/data/MCF7_miR-CTRL4.gene.FPKM.xls",
  "~/Documents/MSC_project/data/MCF7_miR-D1.gene.FPKM.xls", "~/Documents/MSC_project/data/MCF7_miR-D2.gene.FPKM.xls", "~/Documents/MSC_project/data/MCF7_miR-D3.gene.FPKM.xls", "~/Documents/MSC_project/data/MCF7_miR-D4.gene.FPKM.xls"), 
  nrow=8, ncol=4))

colnames(samples_eg) <- c("Sample", "Condition", "Replicate", "FilePath")
```

```{r}
#read & tidy

#keep first gene name
get_first_item <- function(x){
  split <- strsplit(x, ",")
  return(split[[1]][1])
}
```

```{r}

#clean up files, write out

samp_n = 0

for (i in samples_eg$FilePath) {
  
  samp_n <- samp_n + 1 
  status <- if (samp_n <= 4) status = "Control" else status = "Mutant"
  files <- read.csv(i, header=T, sep="\t")
  colnames(files) <- c("gene_id", "transcript_id", "effective_length", "expected_count", "FPKM")
  files$transcript_id <- as.character(files$transcript_id)
   
    for(j in 1:nrow(files)){
    
      row <- files[j,]
      tx_list <- row$transcript_id
      item <- get_first_item(tx_list)
      files[j,2] <- item
  
    }
  
  #calculate TPM from FPKM; (provided by Colin Dewley of RSEM)
  #https://groups.google.com/forum/#!topic/rsem-users/W9RQrZIOzA4
  
  #have checked values sum to million
  
  files$TPM= ( files$FPKM / sum(files$FPKM) * 10^6)
  
  myfile <- file.path("~/Desktop/project_prac", paste0('cleaned_MCF7_', status, counter, ".txt", sep = ""))
  write.table(files, myfile, col.names = T, row.names = F) 
}



```
